plugins {
    id("groovy")
    id("io.micronaut.library") version "4.6.1"
    id("io.micronaut.aot") version "5.0.2"
    id("com.gradleup.shadow") version "8.3.6"
    id("maven-publish")
}

// TODO: Update group and version number if applicable
group = 'org.maurodata.plugins'
version = '0.0.2-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly("io.micronaut.groovy:micronaut-runtime-groovy")
    compileOnly("io.micronaut:micronaut-jackson-databind")
    compileOnly("io.micronaut.security:micronaut-security-annotations")
    compileOnly("io.micronaut.security:micronaut-security-session")
    compileOnly("io.micronaut:micronaut-inject-groovy")
    compileOnly("io.micronaut.data:micronaut-data-processor")
    // runtimeOnly("org.yaml:snakeyaml")

    compileOnly("io.micronaut:micronaut-core-reactive")
    aotPlugins("io.micronaut:micronaut-core-reactive")

    // Change this to depend on a different version of Mauro
    compileOnly('org.maurodata:mauro-domain:0.0.2-beta')
    compileOnly('org.maurodata:mauro-persistence:0.0.2-beta')
    compileOnly('org.maurodata:mauro-api:0.0.2-beta')

    implementation('org.freemarker:freemarker:2.3.34')
}

micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("uk.ac.ox.softeng.mauro.*", "org.maurodata.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

plugins.withId("maven-publish") {
    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                from(components["java"])
                artifactId = "${rootProject.name}"
            }
        }

        repositories {
            maven {
                name = "MauroSnapshotRepository"
                url = "https://mauro-repository.com/libs-snapshot-local"
                credentials(PasswordCredentials)
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
    }
}
